### ISSUE TITLE
website

### ISSUE THREAD

**Issue by maxbachmann** [ToolboxBodensee/toolbox-netzwerk#12]
ka wie das aktuell gehandhabt wird, aber ich denke wir sollten auch das Apache Zeugs für die Webseite mit in ein ansible skript packen.
Die Header für die Webseite sind aktuell beispielsweise wieder falsch gesetzt (im Februar waren diese das noch nicht)

**Comment by DO1JLR** [comment]
Natürlich sollte man das. Aber auf den betroffenen Server wird aktuell nichts mit Ansible ausgerollt.

Der Server wird primär von Mart verwaltet...

**Comment by maxbachmann** [comment]
hm dann merke ich zumindest mal an dass ich mit der Verwaltung etwas unzufrieden bin o.0
Ist nicht so richtig toll wenn jedesmal wenn ich die Header prüfe wieder alles weg ist (ist ja durchaus nicht das erste mal), sondern immer ein ich merke die Fehlenden header an, diese werden Hinzugefügt, zwei Monate später schaue ich wieder und diese sind jedes Mal wieder weg
https://observatory.mozilla.org/analyze/toolbox-bodensee.de

**Comment by DO1JLR** [comment]
wegen inaktivität geschlossen
