### ISSUE TITLE
IPv6 läuft nicht stabil

### ISSUE THREAD

**Issue by DO1JLR** [ToolboxBodensee/toolbox-netzwerk#3]
IPv6 hat manchmal aussetzer und läuft nicht immer. Das ist sehr schade.

Grund dafür kann dieses nicht zu 100% funktionierendes ``wide-dhcpv6-client`` sein.

Hier bedarf es kompetente hilfe!

**Comment by DO1JLR** [comment]
es war ein zweiter radvd im netzt... könnte was geholfen haben...

**Comment by DO1JLR** [comment]
Kleines Update hier, was los ist:

Daa ppp0 Interface hat IPv6 und läuft stabil.

Das LAN (enp1s0) hat einen festen prefix vod der Telekom.

Dieser muss per dhcpv6 Request beantragt werden.

Ein Tool, dass das theoretisch kann, ist der ``winde-dhcpv6-client``.

### Aber:
wide-dhcpv6-client ist leider nicht nir veraltet oletzter commit 2006) sondern funktioniert auch nicht und kann auch kein systemd.

Das Lease wurde mit der Telekom nicht ordentlich ausgehandelt und nach wenigen Minuten bis stunden bricht die ipv6 route zusammen.

Eine (vermutlich) gute Idee wäre, das ganze gegen einen moderneren IPv6 DHCP Client zu ersetzen.

Das könnte dhcpcd5 oder was anderes sein... hatte bisher halt leider nicht funktioniert...

**Comment by rtt-mmk** [comment]
ich favorisiere hier für solche Geschichten mal PowerDNS / PDNS - https://packages.debian.org/de/stretch/pdns-backend-bind
ohne mich bisher wirklich ausreichend damit beschäftigt zu haben. aber es gibt stellen, wo sowas damit sehr stabil und gut läuft... https://blog.luukhendriks.eu/2015/12/01/ipv6-only-network-at-home.html und auch in öffentlichen Clouds ;-)

**Comment by DO1JLR** [comment]
Nunja, das PowerDNS kann/macht wohl sinn mit TAYGA und DNS64. 

Wir haben hier aber "natives" IPv6 der telekom. das wird aber nicht ordentlich geroutet. 

Keine ahnung was da wirklich schief ist. DNS einträge manipulieren hilft da aber nicht.

**Comment by rtt-mmk** [comment]
just a few bookmarks (hauptsächlich dafür, dass ich sie nachher in der Toolbox noch finde...)
https://www.pro-linux.de/artikel/2/1871/ipv6-konfiguration-eines-linux-dsl-gateways.html

https://unix.stackexchange.com/questions/28106/dhcpv6-prefix-delegation-server-for-linux
https://telekomhilft.telekom.de/t5/Geraete-Zubehoer/interne-IPv6-Wie-bekommen-Cpomputer-im-LAN-eine-IPv6-wenn-DHCP/td-p/1449811

https://www.mcseboard.de/topic/208606-ipv6-im-netzwerk-2012r2-dhcp/

https://en.wikipedia.org/wiki/Comparison_of_DHCP_server_software

https://serverfault.com/questions/829950/debian-ipv6-dhcp-not-working-when-rebooting
https://www.linux-magazin.de/ausgaben/2015/11/dhcpy6d/

**Comment by DO1JLR** [comment]
Achtung: DHCP Server sind **keine** DHCP Clients!!!

**Comment by DO1JLR** [comment]
Mit dem Unify Gateway funktioniert auch IPv6 :man_shrugging:
