### ISSUE TITLE
SWITCH config manuell überprüfen und reparieren

### ISSUE THREAD

**Issue by DO1JLR** [ToolboxBodensee/toolbox-netzwerk#44]
Der Switch  cheerilee.tbbs.me im Serverraum ist halb-kaputt.

Manche ports scheinen auf admin-down zu sein... oder irgendwie anders kaputt.

Oder spanning tree ist aktiviert und läuft amok.

Alles seit dem alex loops gesteckt hat...

**Comment by rtt-mmk** [comment]
ist das der mit dem Fiber-Uplink nach oben oder der, der hinten anhängt? 

Wenn es der mit dem Uplink ist, tja, dann müsste man kurz das fiber umhängen und an den mal an die Konsole ran. Darum hängen ja z.B. meine Server an beiden mit jeweils einer IP... 


Ansonsten, halt einfach auslassen, erstmal. Bis ich mir den nächstes WE per Konsole direkt anschauen kann. Das würde den Uplink dann ja nicht beeinflussen.

**Comment by DO1JLR** [comment]
Der switch  cheerilee.tbbs.me ist der zentrale core-switch im abgeschlossenen serverraum.

was auf jeden fall defekt sind - sind manche ports. denn nicht überall bekommt man zuverlässig eine IP Adresse. 

Alles sehr random!

**Comment by rtt-mmk** [comment]
aso, das ist der Raum oben. Also um den kann ich kommenden Freitagabend/Samstagvormmitag kümmern. Müsste mir allerdings wer einen Schlüssel für die TB leihen, wenn nicht sowieso wer dort ist.

**Comment by rtt-mmk** [comment]
würde die Ports, die nicht mehr zuverlässig arbeiten im iOS abschalten. Und das anderes so wie oben konfigurieren und passend aktivieren.

**Comment by DO1JLR** [comment]
> würde die Ports, die nicht mehr zuverlässig arbeiten im iOS abschalten. Und das anderes so wie oben konfigurieren und passend aktivieren.

Oder vielleicht erstmal schauen WARUM sie nicht funktionieren und das beheben. weil es vermutlich nur in der config irgend etwas ist...

**Comment by rtt-mmk** [comment]
ok.

**Comment by DO1JLR** [comment]
interface muste von hand resetet werden.

Unschön, aber bei einem loop besser als wenn alles still steht!
