### ISSUE TITLE
Openstack inkompatibel mit den in der Toolbox verwendeten Keys

### ISSUE THREAD

**Issue by rtt-mmk** [ToolboxBodensee/toolbox-netzwerk#55]
Openstack hat keine Unterstützung für die in der Toolbox verwendeten ssh-keys.
Ein Aufsetzen eines Clusters mittels den offizziellen Ansible-Scripten von Openstack (openstack-ansible) ist nicht möglich, ohne die Keys der Server zu ändern.

**Comment by DO1JLR** [comment]
ja schon... aber dennoch ist der einsatz von eliptischer kurven kryptographie iirc möglich!

**Comment by DO1JLR** [comment]
Okay...

Aber dann nutze bitte nicht ``inkompatibel`` sondern ``andere Standardeinstellungen``!!!
