### ISSUE TITLE
OS-4 not accessible

### ISSUE THREAD

**Issue by DO1JLR** [ToolboxBodensee/toolbox-netzwerk#62]
Was ist da los beim os-4?

Der os-1 ist wohl aus????

Der os-4 ist zwar an... aber ohne meinen User?

Situation klären oder machinen hier aus dem ansible kicken!

**Comment by rtt-mmk** [comment]
der os-4 war über 10 Tage lang nicht erreichbar, weil die Openstack-Ansible-Rollen die Routen über ein Interface falsch gesetzt hatten. Jonas hat heute Nachmittag geholfen, das vor Ort zu fixen. Seit dem ist er wieder erreichbar.

Da läuft ein CentOS mit dem kompletten Openstack als All-in-One-Host - sollte auch bis über den Tag der offenen Türe so bleiben. Danach kann man schauen, weitere Hosts an den anzufügen.

Login ist mit dem bekannten Toolbox-pass möglich. Die Toolbox-Ansible Rollen sind (derzeit noch) inkompatibel mit Openstack. bzw würden das Openstack-AIO destroyen. s. #55 

Ja, wie berichtet, der os-1 ist schon länger aus. Habe den aber nicht runtergefahren.

**Comment by rtt-mmk** [comment]
hat sich erledet - der os-4 ist up and running und unter den dokumentierten IPs zu erreichen.

**Comment by DO1JLR** [comment]
https://asciinema.org/a/2dxJ6QcRpf5OmxCktE7pErVBN

Zugang nicht möglich!
